/** Auto-generated by `pnpm tunnel`. Do not edit by hand.
 *  When the tunnel is running, this file is rewritten with the tunnel's
 *  service DID + URL; when the tunnel stops, it is reset to null values. */

export const SERVICE_DID: string | null = "did:web:scroll-heat-flowers-software.trycloudflare.com#event_space";
export const SERVICE_URL: string | null = "https://scroll-heat-flowers-software.trycloudflare.com";
